server:
  port: 9998
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务 设置开启如果没有服务注册进eureka会报错
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #此处必须是驼峰式defaultZone而不是default-zone,不然报错

